### ISSUE TITLE
[API docs] missing info for meta and properties for endpoint /screenshot

### ISSUE THREAD

**Issue by Klaasvaak** [xebia/VisualReview#48]
The API docs mention `screenshotName` and `file` but does not mention the `meta` and `properties`

**Comment by RRMoelker** [comment]
Thank you, we will add that information to the API docs (see PR #49). I understand you needed this for a Node.js implementation. Did you get it working?

We are aware that the API documentation is still lacking a bit at the moment. In the long run, we plan on generating the API docs from the back end models or from something like JSON schema.

**Comment by Klaasvaak** [comment]
Thanks for updating the docs!

I made a node.js client. I can open source it this week, will notify you.

**Comment by Klaasvaak** [comment]
Source is here: https://github.com/Klaasvaak/VisualReview-node-client

Did not use this version of the code yet in my project.
