### ISSUE TITLE
Question regarding CI and different environments / branches

### ISSUE THREAD

**Issue by jasonmacdonald** [xebia/VisualReview#53]
I'm currently in the process of trying to figure out the best use of Visual Review in our current Continuous Integration environment which goes through CI, Dev, QA, Staging and finally production. One of the items I'm struggling with is where Visual Reviews baselines fit in. 

In our current process we have multiple environments that code moves through, and sometimes multiple branches (hotfixes, long running features, etc). Given that the state of the code changes in each of these areas, I'm curious as to your thoughts on the location of baseline images per environment and per versions of release (current vs future release dev code).

My initial thought was to check-in baselines to the code base (basically save the DB) so that each environment starts with a valid set of baselines, but this becomes problematic when deployed to say our QA servers where the QA staff want to update a baseline. That would be saved to the deployed environment, but not into the saved baseline in the project for that branch. The next time a deployment is done that new baseline is overwritten by the one saved in the project.

Any thoughts on how your great project can be used in a multi-environment / multi-version project?

**Comment by skwakman** [comment]
Interesting question. I think it really depends on what exactly you wish to test in these different integration phases. 

Without knowing any context my first thoughts would be to have these phases have their own set of test-scripts as they would probably test different elements of your application and/or using different back-end data to do so. This approach means that these phases have their own suites (or even projects) and their own baselines.
