### ISSUE TITLE
Screenshots are different taken between Chrome and Firefox

### ISSUE THREAD

**Issue by wlsf82** [xebia/VisualReview#55]
When I integrate my Protractor tests with VistualReview, if my capability is Firefox, the taken screenshot is a full screenshot of the page, even with the scroll,  but with Chrome only the visible area is taken.
Is this something specific from Protractor and Visual Review integration?

**Comment by skwakman** [comment]
This is, sadly, a long-running issue in the ChromeDriver component used when running Webdriver tests on webkit-enabled browsers like Chrome, Safari and Opera. The relevant bug report and the long-running discussion around it is here: https://code.google.com/p/chromedriver/issues/detail?id=294 . 

The quickest workaround is to scale chrome's browser window to the area you wish to capture. 

Alternatively, a solution we're currently testing is having VisualReview-protractor capture various screenshots as it's scrolling through the page and stitch them together. However, this introduces all kinds of nasty side-effects with elements that have special behavior in regards to scrolling (position:fixed or javascript-enabled onScroll-triggered logic). We plan to release this workaround as an experimental option in VisualReview-protractor somewhere in the upcoming weeks.

**Comment by skwakman** [comment]
For reference, here's the actual issue of VisualReview-protractor : https://github.com/xebia/VisualReview-protractor/issues/2

It's progress has been stalled for a while due to different priorities, however I expect to finish it somewhere in the next few weeks.

**Comment by skwakman** [comment]
closing issue, will be tracked in xebia/VisualReview-protractor#2
