### ISSUE TITLE
Selenium-VisualReview in C#

### ISSUE THREAD

**Issue by khuberts** [xebia/VisualReview#60]
Hi,

I saw that you have the code for VisualReview-Selenium in Java.

Do you also have it in C#?

**Comment by skwakman** [comment]
Hi,

We don't have any C# integration at this moment, however it should not be too hard to create one yourself. See the [API documentation](https://github.com/xebia/VisualReview/blob/master/doc/api.md) for more details.

**Comment by khuberts** [comment]
I have tried to but i'm not getting it to work.
Can you help me with this?

**Comment by skwakman** [comment]
I'm not exactly fluent in C#, but lets try it anyway. I'd suggest to move this discussion to our Gitter chatroom: https://gitter.im/xebia/VisualReview

**Comment by khuberts** [comment]
How can I use this chatroom i don't really see where our discussion is?

**Comment by skwakman** [comment]
if you click on the link (and login using your github account if it asks to do so) the xebia/VisualReview channel should be visible

**Comment by khuberts** [comment]
I cant acces our chat anymore. it doesnt load the page?
