### ISSUE TITLE
Suite status API resource not found

### ISSUE THREAD

**Issue by RRMoelker** [xebia/VisualReview#64]
After many runs ( > 3500 runs) the status resource suddenly returned a 404. Deleting the last few runs in that suite fixed the problem. I could not find a VR log with any errors. But it is quite clear that the end point is not working as expected.

I'm not expecting the issue to be fixed given the limited bug report. But it is a indication that more logging is desired.

```
Sending request to url:
http://<VR_SERVER>/api/projects/1/suites/3/status
Response Code: HTTP/1.1 404 Not Found
```

**Comment by skwakman** [comment]
do you still have the database file (`visualreview.db.mv.db`) that triggered the error? I could use that to find the problem.

**Comment by RRMoelker** [comment]
Alas, no. I removed the last runs through the UI forgetting to make a DB backup first.

I suggest closing the issue for now as it probably is very hard to reproduce. When it reoccurs I'll extract the db.

**Comment by skwakman** [comment]
I'm guessing one the last runs triggered something weird in the internal storage, causing the 404's. If you encounter this error again, you could re-open this issue.
