### ISSUE TITLE
Baseline not set correctly when 1st image rejected and 2nd accepted

### ISSUE THREAD

**Issue by sibbl** [xebia/VisualReview#75]
Hi all,

I rejected my first screenshot as it had a small mistake in it. Thus, I started taking another screenshot and accepted this 2nd one. However, I couldn't compare upcoming screenshots with a baseline - the radio buttons in the UI were disabled. Did I do anything wrong or how is this supposed to work?

**Comment by sibbl** [comment]
Unfortunately I now tried every possible way to reproduce it and of course now it works as expected. This is very strange but I'm glad I now understood how the baseline is set.

**Comment by skwakman** [comment]
Glad it worked out. If it happens again, let me know.
