### ISSUE TITLE
I cannot click on the "Baseline" radio - no error returned in browser console.

### ISSUE THREAD

**Issue by jaffamonkey** [xebia/VisualReview#78]
I cannot click on the "Baseline" radio - no error returned in browser console.  Tried in Safari/Firefox/Chrome with no success.

**Comment by skwakman** [comment]
is it greyed out? It should be greyed out if there's no baseline yet. This happens if you're viewing a screenshot which does not have an `accepted` version yet.

**Comment by jaffamonkey** [comment]
Ah of course :) Thanks for your very prompt response!
